#!/usr/bin/perl
my ($n) = @ARGV;
$n = 1000000 if not $n;
open FH, ">distr";
my $z = 0;
for my $i (1..20) {
  if (-e "OUT/trace$i.txt") {
    #print "distr for run $i\n";
    $n = `wc -l OUT/trace$i.txt | awk '{print $1}'`;
    # system "head -n $n OUT/trace$i.txt > tmp";
    # print "n = $n\n";
    my @places = qw/N H C S O W/;
    my $tot = 0.0;
    for my $p (@places) {
      my $x = `grep "at $p" OUT/trace$i.txt | wc -l | awk '{print $1}' `;
      # my $x = `grep "at $p" tmp | wc -l | awk '{print $1}' `;
      my $ave = 100.0 * $x / $n;
      $tot += $ave;
      printf FH "%6.2f ", $ave;
    }
    printf FH "\n";
    $z = $i;
  }
}
close FH;
my $mean;
my $std;
($n, $mean, $std) = split " ", `/Users/gref/bin/ave_std distr 1`;
printf "N %5.2f %4.2f %d\n", $mean, $std, $n;  
($n, $mean, $std) = split " ", `/Users/gref/bin/ave_std distr 2`;
printf "H %5.2f %4.2f %d\n", $mean, $std, $n;  
($n, $mean, $std) = split " ", `/Users/gref/bin/ave_std distr 3`;
printf "C %5.2f %4.2f %d\n", $mean, $std, $n;  
($n, $mean, $std) = split " ", `/Users/gref/bin/ave_std distr 4`;
printf "S %5.2f %4.2f %d\n", $mean, $std, $n;  
($n, $mean, $std) = split " ", `/Users/gref/bin/ave_std distr 5`;
printf "O %5.2f %4.2f %d\n", $mean, $std, $n;  
($n, $mean, $std) = split " ", `/Users/gref/bin/ave_std distr 6`;
printf "W %5.2f %4.2f %d\n", $mean, $std, $n;  



