#!/usr/bin/perl
my ($n) = @ARGV;
$n = 1000000 if not $n;
open FH, ">age.distr";
my $n = 0;
my %age_exposed = ();
my %age_count = ();
for my $i (0..8) {
  my $age = 10*$i;
  $age_exposed{$age} = 0;
  $age_count{$age} = 0;
}
for my $i (1..20) {
  my $file = "OUT/trace$i.txt";
  next if not -e "OUT/trace$i.txt";
  open TR, $file;
  while (my $line = <TR>) {
    my @a = split " ", $line;
    my $age = $a[5];
    my $low = $age - ($age % 10);
    $age_count{$low}++;
    $age_exposed{$low}++ if ($a[1] ne 'S') and ($a[1] ne 'M');
    $n++;
  }
  close TR;
}
for my $i (0..8) {
  my $age = 10*$i;
  my $x = 100 * $age_exposed{$age} / $age_count{$age} if $age_count{$age};
  printf FH "%d %d %5.2f %d %d\n", $age, $age+9, $x, $age_count{$age}, $age_exposed{$age};
}
close FH;
system "cat age.distr";





