#!/usr/bin/perl
use strict;
use warnings;

open FH, "alleg.txt";
# open PLACE, ">place.txt";
# open SCH, ">sched.txt";

my @data = <FH>;
close FH;

# create pop array
my @pop = ();
my $id = 0;
for (@data) {
  chomp;
  my ($block, $house, $occ, $age, $sex, $lat, $lon, $school, $work) =
  split;
  $sex = ($sex == 1)? "M": "F";
  push @pop, "$id $age $sex";
  $id++;
}


# create loc hash
my %loc = ();
for (@data) {
  chomp;
  my ($block, $house, $occ, $age, $sex, $lat, $lon, $school, $work) =
  split;
  while (length $house < 4) { $house = "0$house" }
  my $houseid = $block . $house;

  $loc{"$houseid"} = "H $lat $lon";

  if ($school > 0) {
    $loc{"$school"} = "S 0 0";
  }

  if ($work > 0) {
    $loc{"$work"} = "W 0 0";
  }
}

# re-label hospitals
open HOS, "AL_hospitals.txt";
while (<HOS>) {
  chomp;
  my ($hosp) = split;
  $loc{$hosp} = "C 0 0";
}
close HOS;

# re-label school workplaces by their school field id
my %school_map = ();
open SCHOOL, "AL_teachers.txt";
while (<SCHOOL>) {
  chomp;
  my ($school_w, $school_s) = split;
  $school_map{$school_w} = $school_s;
  # print "$school_w  $school_s\n";
  # remove school workplace ids from the location list
  if (exists $loc{$school_w}) {
    delete $loc{$school_w};
  }
}
close SCHOOL;

# map loc id to array index
my @place = ();
my %pmap = ();
$id = 0;
for my $key (sort keys %loc) {
  push @place, "$id $key $loc{$key}";
  $pmap{$key} = $id;
  $id++;
}


# create schedule file
open SCHED, ">sched.txt";
$id = 0;
for (@data) {
  chomp;
  my ($block, $house, $occ, $age, $sex, $lat, $lon, $school, $work) =
  split;
  while (length $house < 4) { $house = "0$house" }
  my $houseid = $block . $house;
  for my $day (0..6) {
    print SCHED "$id $day $pmap{$houseid}\n";
  }
  if ($school > 0) {
    for my $day (1..5) {
      print SCHED "$id $day $pmap{$school}\n";
    }
  }
  if ($work > 0) {
    if (exists $school_map{$work}) {
      $work = $school_map{$work} if exists $school_map{$work};
    }
    for my $day (1..5) {
      print SCHED "$id $day $pmap{$work}\n";
    }
  }
  $id++;
}
close SCHED;


open POP, ">pop.txt";
print POP "Population = ", scalar @pop, "\n";
for my $i (0..$#pop) {
  print POP "$pop[$i]\n";
}
close POP;

open LOC, ">loc.txt";
print LOC "Locations = ", scalar @place, "\n";
for my $i (0..$#place) {
  print LOC "$place[$i]\n";
}
close LOC;

exit;
 
