#!/bin/csh -f
if (! -d OUT.TEST) mkdir OUT.TEST
./FRED params.test > OUT.TEST/LOG
cmp OUT.TEST/out1.txt TEST/out1.txt
cmp OUT.TEST/out2.txt TEST/out2.txt
cmp OUT.TEST/trace1.txt TEST/trace1.txt
cmp OUT.TEST/trace2.txt TEST/trace2.txt
echo regression test finished.
