#!/bin/csh -f
if (! -d OUT.TEST) mkdir OUT.TEST
./FRED params.test > OUT.TEST/LOG
cmp OUT.TEST/out1.txt OUT.RT/out1.txt
cmp OUT.TEST/out2.txt OUT.RT/out2.txt
cmp OUT.TEST/trace1.txt OUT.RT/trace1.txt
cmp OUT.TEST/trace2.txt OUT.RT/trace2.txt
echo regression test finished.
