age:
  #intervals: [0, 0.5, {'from':1,'to':95,'by':1}, 100]
  #intervals: [{'from':0,'to':120,'by':1}]
  intervals: [0, 19, 65, 100]

income:
  intervals: [{'from': 0, 'to': 100000, 'by': 10000}, 200000, 400000]

#gender:

#race:

place_type:

#longitude:
#  intervals: 20

#latitude:
#  intervals: 20


